# Generated by Django 4.2.1 on 2023-06-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djcrm_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='organisation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
