# Generated by Django 4.2.2 on 2023-06-19 11:51

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item_app', '0003_alter_category_options_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversation_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Converstion',
            new_name='Conversation',
        ),
    ]
